version: '3.8'

services:
  zulipchat-mcp:
    build: .
    image: akougkas/zulipchat-mcp:latest
    container_name: zulipchat-mcp
    restart: unless-stopped
    environment:
      - ZULIP_EMAIL=${ZULIP_EMAIL}
      - ZULIP_API_KEY=${ZULIP_API_KEY}
      - ZULIP_SITE=${ZULIP_SITE}
      - MCP_PORT=${MCP_PORT:-3000}
      - MCP_DEBUG=${MCP_DEBUG:-false}
    ports:
      - "${MCP_PORT:-3000}:3000"
    volumes:
      # Optional: Mount config directory for file-based configuration
      - ~/.config/zulipchat-mcp:/app/.config/zulipchat-mcp:ro
    secrets:
      # Optional: Use Docker secrets for sensitive data
      - zulip_api_key
      - zulip_email
      - zulip_site
    healthcheck:
      test: ["CMD", "python", "-c", "from src.zulipchat_mcp.config import ConfigManager; ConfigManager().validate_config()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Optional Docker secrets (recommended for production)
secrets:
  zulip_api_key:
    external: true
  zulip_email:
    external: true
  zulip_site:
    external: true